### ISSUE TITLE
[Collection] Text formatting issues in Marker names

### ISSUE THREAD

**Issue by recon88** [webbukkit/dynmap#2288]
Putting single quotes in marker names are being displayed as the HTML character `&#39;`  
  
Example:  
`recon's house` is being displayed as `recon&#39;s house` on the live map

**Comment by TomSputz** [comment]
There is currently no version compiled for 1.13, afaik it is still in the works (Last commit 5 hours ago), but it is currently not possible to use dynmap with 1.13

**Comment by recon88** [comment]
@TomSputz you must have missed the 1.13 builds ;) It's working for quite a while now.
You can follow the progress here: https://github.com/webbukkit/dynmap/issues/2271

**Comment by TomSputz** [comment]
Huh. I'd completely failed to get it to build and assumed it was simply because spigot 1.13 is hardly out. Thanks!

**Comment by therealhazmatt** [comment]
It appears as though single quotes (code 39) are still not working:
`Somebody's Base` is displayed as `Somebody&#39;s Base`.

However, if a "fancy" single quote is used (code 8217), it works:
`Somebody’s Base` is displayed as `Somebody’s Base`.
If you add a marker via the `/dmarker add` command, it uses the fancy single quote.

I'm working on a method to build the `markers.yml` file from a database I built, so I have been paying close attention to formatting things.  As such, I am able to substitute fancy quotes instead of plain quotes.

Dynmap version: core=3.0-SNAPSHOT-163, plugin=3.0-SNAPSHOT-163
Spigot 1.13.2 (01/04/2019) [Latest]

**Comment by DankRank** [comment]
Here (and throughout the rest of that function) the label text gets sanitized prior to being written to `marker_<world>.json`
https://github.com/webbukkit/dynmap/blob/1be9f663c751f9b5084e8134dca37f319d7a3d35/DynmapCore/src/main/java/org/dynmap/markers/impl/MarkerAPIImpl.java#L2999
Meanwhile on the webclient, the markup flag is checked, and if it is set, the label is interpreted as html, otherwise it's inserted as a text node.
https://github.com/webbukkit/dynmap/blob/1be9f663c751f9b5084e8134dca37f319d7a3d35/DynmapCore/src/main/resources/extracted/web/js/markers.js#L108-L120
When markup is set to false, the html entities that were created by the server simply never get decoded by the browser.
This is the commit in which it was broken: https://github.com/webbukkit/DynmapCore/commit/ca39c1cc5ab3dac6644bbc5489e4b03a20f52a5c
The label name doesn't get sanitized in "markerupdated" messages, which means that when you first create the marker it will look fine until you refresh the page, at which point the label will be taken from json file.

**Comment by Cretezy** [comment]
Any update on this? Seems like it's still happening with 3.1-beta4

**Comment by mhbates** [comment]
Confirmed happening with 3.1-beta5.

**Comment by JurgenKuyper** [comment]
can confirm accent-grave (`) still gives &#96 on the map, the ' is fixed though.

**Comment by mikeprimm** [comment]
Fixed in 3.3

**Comment by generrosity** [comment]
I see a thumbs up from DarkRank - I don't suppose @recon88 @therealhazmatt @Cretezy @mhbates you have checked out the latest 3.3 big-ish release or the latest snapshots to confirm?

**Comment by therealhazmatt** [comment]
> I see a thumbs up from DarkRank - I don't suppose @recon88 @therealhazmatt @Cretezy @mhbates you have checked out the latest 3.3 big-ish release or the latest snapshots to confirm?

No, it's actually been a long time since I've used DynMap.  But, I'm glad to see this finally getting some attention.  ;)

**Comment by recon88** [comment]
Looks good to me.

Only a small issue to mention:
```
/dmarker add "recon's recon`s recon´s house" icon:anchor set:homes
```
outputs
```
[Render thread/INFO]: [CHAT] Added marker id:'marker_3' (recon&#39;s recon`s recon´s house) to set 'homes'
```
But it still shows properly on the map.

**Comment by DankRank** [comment]
I haven't actually checked it either.

**Comment by mikeprimm** [comment]
Yep - that is works as designed - those are the HTML escaped versions.   I'm not going to unconvert them just for the damned command line feedback.
